Repository Freescale/meta-freescale, pull requests merged in 2025-01, with the labels that each got.

#2058 linux-fslc-imx: Use 6.6-2.2.0.x from NXP BSP LF6.6.52_2.2.0
  recipes-kernel/linux/linux-fslc-imx_6.6.bb
Labels: backport scarthgap

#2063 glmark: Simplify logic for DRM config
  dynamic-layers/openembedded-layer/recipes-benchmark/glmark2/glmark2_%.bbappend
Labels: backport scarthgap

#2062 linux-fslc-imx: bump to add one bugfix
  recipes-kernel/linux/linux-fslc-imx_6.6.bb
Labels: backport scarthgap

#2060 imx-base: Avoid unnecessary device tree blob files
  conf/machine/include/imx-base.inc
Labels: backport scarthgap

#2053 Update kernel and jailhouse to L6.6.52_2.0.0
  conf/machine/imx8mp-lpddr4-evk.conf
  conf/machine/imx8qm-mek.conf
  conf/machine/imx8qxp-mek.conf
  conf/machine/imx8ulp-lpddr4-evk.conf
  conf/machine/imx93-9x9-lpddr4-qsb.conf
  conf/machine/include/imx8x-mek.inc
  recipes-extended/jailhouse/jailhouse-imx_git.bb
  recipes-kernel/linux/linux-imx-headers_6.6.bb
  recipes-kernel/linux/linux-imx_6.6.bb
Labels: backport scarthgap

#2069 Gstreamer: Upgrade to LF-6.6.52_2.2.0
  conf/machine/include/imx-base.inc
  recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad/0001-autovideoconvert-add-imxvideoconvert_g2d.patch
  recipes-multimedia/gstreamer/gstreamer1.0-plugins-bad_1.24.7.imx.bb
  recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.24.7.imx.bb
  recipes-multimedia/gstreamer/gstreamer1.0-plugins-base_1.24.7.imx.bbappend
  recipes-multimedia/gstreamer/gstreamer1.0-plugins-good_1.24.7.imx.bb
  recipes-multimedia/gstreamer/gstreamer1.0/0001-tests-respect-the-idententaion-used-in-meson.patch
  recipes-multimedia/gstreamer/gstreamer1.0/0002-tests-add-support-for-install-the-tests.patch
  recipes-multimedia/gstreamer/gstreamer1.0/0003-tests-use-a-dictionaries-for-environment.patch
  recipes-multimedia/gstreamer/gstreamer1.0/0004-tests-add-helper-script-to-run-the-installed_tests.patch
  recipes-multimedia/gstreamer/gstreamer1.0_1.24.7.imx.bb
  recipes-multimedia/gstreamer/imx-gst1.0-plugin_git.bb
Labels: backport scarthgap

#2061 Upstream from NXP-6.6.52-2.0.0
  recipes-bsp/qe-ucode/qe-ucode_git.bb
  recipes-devtools/qoriq-cst/qoriq-cst_git.bb
  recipes-dpaa2/dce/dce_git.bb
  recipes-dpaa2/restool/restool_git.bb
Labels: backport scarthgap

#2073 linux-imx: Remove obsolete patch file
  recipes-kernel/linux/linux-imx/0001-lib-build_OID_registry-don-t-mention-the-full-path-o.patch
  recipes-kernel/linux/linux-imx/0001-video-logo-Drop-full-path-of-the-input-filename-in-g.patch
  recipes-kernel/linux/linux-imx_6.6.bb
Labels: backport scarthgap

#2087 scripts: avoid pointless LICENSE churn
  scripts/generate-license-file
Labels: backport styhead

#2079 firmware-ele-imx: Use generic-bsp compatible
  recipes-bsp/firmware-imx/firmware-ele-imx_1.3.0.bb
Labels: backport scarthgap, backport styhead

#2094 Fix dtb changes for 6.6.52_2.0.0
  conf/machine/imx8qm-mek.conf
  conf/machine/imx8qxp-mek.conf
  conf/machine/imx8ulp-lpddr4-evk.conf
  conf/machine/include/imx8x-mek.inc
Labels: backport scarthgap, backport styhead

#2097 firmware-upower: SRC_URI uses PN not BPN
  recipes-bsp/firmware-upower/firmware-upower_1.3.1.bb
Labels: backport scarthgap, backport styhead

#2101 linux-fslc-imx: Update 6.6-2.2.x to stable v6.6.74
  recipes-kernel/linux/linux-fslc-imx_6.6.bb
Labels: backport scarthgap, backport styhead

#2104 Set default UBOOT_ENTRYPOINT for mx93-generic-bsp
  conf/machine/include/imx-base.inc
Labels: backport scarthgap, backport styhead
