Repository Freescale/meta-freescale, pull requests merged in 2025-04, with the labels that each got.

#2178 kernel-module-nxp-wlan: Apply wireless patch
  recipes-kernel/kernel-modules/kernel-module-nxp-wlan/wlan_src_driver_patch_release_lf-6.6.52-2.2.0.patch
  recipes-kernel/kernel-modules/kernel-module-nxp-wlan_git.bb
Labels: backport scarthgap, backport styhead

#2182 opencv: Specify right path for <numpy/ndarrayobject.h>
  recipes-support/opencv/opencv_4.6.0.imx.bb
Labels: backport scarthgap, backport styhead

#2186 Revert "opencv: Specify right path for <numpy/ndarrayobject.h>"
  recipes-support/opencv/opencv_4.6.0.imx.bb
Labels: backport scarthgap

#2190 kernel-module-nxp-wlan: Add Upstream-Status
  recipes-kernel/kernel-modules/kernel-module-nxp-wlan/wlan_src_driver_patch_release_lf-6.6.52-2.2.0.patch
Labels: backport scarthgap, backport styhead

#2197 Master: Update EULA to v58 and firmware-imx to v8.27
  EULA
  classes/fsl-eula-unpack.bbclass
  recipes-bsp/firmware-imx/firmware-imx-8.27.inc
  recipes-bsp/firmware-imx/firmware-imx_8.27.bb
  recipes-bsp/firmware-imx/imx-boot-firmware-files_8.27.bb
Labels: backport styhead

#2193 u-boot-imx: Update source revision
  recipes-bsp/u-boot/u-boot-imx-common_2024.04.inc
  recipes-bsp/u-boot/u-boot-imx_2024.04.bb
Labels: backport styhead

#2201 fix(opencv): do not try to install sample files
  recipes-support/opencv/opencv_4.6.0.imx.bb
Labels: backport scarthgap, backport styhead

#2204 kernel-module-nxp-wlan: remove COMPATIBLE_MACHINE
  recipes-kernel/kernel-modules/kernel-module-nxp-wlan_git.bb
Labels: backport scarthgap, backport styhead

#2209 imx-boot: add LPDDR_FW_VERSION to mkimage arguments for iMX95
  recipes-bsp/imx-mkimage/imx-boot_1.0.bb
Labels: backport scarthgap, backport styhead

#2218 recipes: fix whitespace warnings
  recipes-bsp/atf/qoriq-atf_2.6.bb
  recipes-bsp/imx-lib/imx-lib_git.bb
  recipes-bsp/rcw/rcw_git.bb
  recipes-devtools/qemu/qemu.inc
  recipes-extended/dpdk/dpdk-module_20.11.bb
  recipes-kernel/ceetm/ceetm_git.bb
  recipes-security/optee-imx/optee-fslc.inc
  recipes-security/smw/smw_git.bb
  recipes-support/opencv/opencv_4.6.0.imx.bb
Labels: backport styhead

#2221 asound.conf: default sample rate to 48000
  recipes-bsp/alsa-state/alsa-state/imx-mainline-bsp/asound.conf
  recipes-bsp/alsa-state/alsa-state/imx-nxp-bsp/asound.conf
Labels: backport scarthgap, backport styhead

#2225 linux-fslc-imx: Bump stable vertion up to 6.6.84
  recipes-kernel/linux/linux-fslc-imx_6.6.bb
Labels: backport styhead
